{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Patient_Name_Main",
    "label": "Patient_Name",
    "query": "Select name from mhdp.device_id;"
   }
  ]
 },
 "panels": [
  {
   "title": "User Details",
   "type": "table",
   "description": "User-level information can be accessed here.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select user_id,device_id, name, contact from mhdp.device_id \n  where device_id in (SELECT i.device_id FROM mhdp.device_id i where i.name in ($Patient_Name_Main))\norder by user_id,device_id;"
    }
   ]
  },
  {
   "title": "Top 10 Patients",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select x.user_id,x.device_id, x.name, x.contact from mhdp.device_id x,mhdp.Triaging_Table  y \nwhere x.user_id = y.userId;\n"
    }
   ]
  },
  {
   "title": "WorkList",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT y.name,x.* FROM mhdp.worklist_Table x, mhdp.device_id y\nwhere x.userId = y.user_id\nand x.status = 'Pending'\nand y.name in ($Patient_Name_Main);\n"
    }
   ]
  }
 ]
}