{
 "title": "Main Dashboard",
 "time": { "from": "2020-11-21T15:45:11.017Z", "to": "2020-11-27T17:54:59.852Z" },
 "templating": {
  "list": [
   {
    "name": "Patient_Name",
    "label": "Patient_Name",
    "query": "SELECT name FROM mhdp.device_id;"
   },
   {
    "name": "Image",
    "query": "select image from mhdp.device_id where name in ($Patient_Name);"
   },
   {
    "name": "Patient_Id",
    "label": "Patient_Id",
    "query": "select i.user_id from mhdp.device_id i where i.name in ($Patient_Name);"
   }
  ]
 },
 "panels": [
  {
   "title": "Image",
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src= $Image width=200 height=200>\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  userId\nFROM worklist_Table\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Questionnaire",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT q1.patient_id,q1.healthworker_id,q2.*,q1.status FROM mhdp.Questionnaire_table q1, mhdp.Questions_table q2\nwhere q1.questionnaire_id = q2.questionnaire_id\nand q1.status='Completed'\nand q1.patient_id in (select i.user_id from mhdp.device_id i where i.name in ($Patient_Name))\nand q1.questionnaire_id in (select max(x.questionnaire_id) from mhdp.Questionnaire_table x where x.patient_id=q1.patient_id  and x.status='Completed');"
    }
   ]
  },
  {
   "title": "Generate QOL",
   "type": "speakyourcode-button-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "insert into mhdp.Questionnaire_table (patient_id, status)\nVALUES ($Patient_Id,\"Pending\");"
    }
   ]
  },
  {
   "title": "Contact Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 9 },
   "targets": [
    {
     "rawSql": "select name,contact from mhdp.device_id where name in ($Patient_Name);\n"
    }
   ]
  },
  {
   "title": "Device Usage",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as \"time\",\n  sum( data->>'$.elapsed_device_on' )\n  AS \"Device ON\"\nFROM `mhdp`.`plugin_device_usage`\nWHERE\n  device_id in (SELECT i.device_id FROM mhdp.device_id i where i.name in ($Patient_Name))\nGROUP BY 1\nORDER BY timestamp\n"
    }
   ]
  },
  {
   "title": "Call Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select x.timestamp as \"time\",y.name,sum(data->>'$.call_duration') as \"call_duration\" from mhdp.calls x , mhdp.device_id y\nwhere x.device_id = y.device_id\nand x.data->>'$.call_type' = 4\nand y.name in ($Patient_Name)\ngroup by x.timestamp,y.name,x.data->>'$.call_type'\n\n"
    }
   ]
  },
  {
   "title": "Plugin Activity Analysis",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as \"time\", data->>'$.is_user_active' as \"is_user_active\", data->>'$.high_activity_time' as \"high_activity_time\", data->>'$.moderate_activity_time' as \"moderate_activity_time\"\nFROM mhdp.plugin_activity_analysis i\nwhere i.device_id in (SELECT x.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))\n"
    }
   ]
  },
  {
   "title": "Ambient Noise",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(data->>'$.double_decibels') AS \"Average Decibels\",\n  avg(data->>'$.double_frequency') AS \"Average Frequency\",\n  avg(data->>'$.double_silence_threshold') AS \"Threshold\"\nFROM `mhdp`.`plugin_ambient_noise`\nwhere device_id in (SELECT i.device_id FROM mhdp.device_id i where i.name in ($Patient_Name))\n"
    }
   ]
  },
  {
   "title": "Google Activity Recognition",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT i.data->>'$.activity_name' , count(1) Still from mhdp.plugin_google_activity_recognition i \nwhere i.device_id in (SELECT x.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))\nand i.data->>'$.activity_name' = 'still'\ngroup by i.data->>'$.activity_name'"
    },
    {
     "rawSql": "SELECT i.data->>'$.activity_name' , count(1) Tilting from mhdp.plugin_google_activity_recognition i  \nwhere i.device_id in (SELECT i.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))\nand i.data->>'$.activity_name' = 'tilting'\ngroup by i.data->>'$.activity_name'"
    },
    {
     "rawSql": "SELECT i.data->>'$.activity_name' , count(1) On_Foot from mhdp.plugin_google_activity_recognition i \nwhere i.device_id in (SELECT i.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))\nand i.data->>'$.activity_name' = 'on_foot'\ngroup by i.data->>'$.activity_name'"
    },
    {
     "rawSql": "SELECT i.data->>'$.activity_name' , count(1) Cycling from mhdp.plugin_google_activity_recognition i  \nwhere i.device_id in (SELECT i.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))\nand i.data->>'$.activity_name' = 'cycling'\ngroup by i.data->>'$.activity_name'"
    },
    {
     "rawSql": "SELECT i.data->>'$.activity_name' , count(1) Unknown from mhdp.plugin_google_activity_recognition i \nwhere i.device_id in (SELECT i.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))\nand i.data->>'$.activity_name' = 'unknown'\ngroup by i.data->>'$.activity_name'"
    }
   ]
  },
  {
   "title": "Tone Name",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "\nselect i.data->>'$.tone_name' ,count(1) Fear from mhdp.tone_analysis i \n where i.device_id in (SELECT x.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))\n and i.data->>'$.tone_name' = 'Fear'\ngroup by i.data->>'$.tone_name';\n\n"
    },
    {
     "rawSql": "select i.data->>'$.tone_name' ,count(1) Joy from mhdp.tone_analysis i \n where i.device_id in (SELECT x.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))\n and i.data->>'$.tone_name' = 'Joy'\ngroup by i.data->>'$.tone_name';"
    },
    {
     "rawSql": "select i.data->>'$.tone_name' ,count(1) Analytical from mhdp.tone_analysis i \n where i.device_id in (SELECT x.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))\n and i.data->>'$.tone_name' = 'Analytical'\ngroup by i.data->>'$.tone_name';"
    },
    {
     "rawSql": "select i.data->>'$.tone_name' ,count(1) Tentative from mhdp.tone_analysis i \n where i.device_id in (SELECT x.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))\n and i.data->>'$.tone_name' = 'Tentative'\ngroup by i.data->>'$.tone_name';"
    },
    {
     "rawSql": "select i.data->>'$.tone_name' ,count(1) Confident from mhdp.tone_analysis i \n where i.device_id in (SELECT x.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))\n and i.data->>'$.tone_name' = 'Confident'\ngroup by i.data->>'$.tone_name';"
    },
    {
     "rawSql": "select i.data->>'$.tone_name' ,count(1) NO_TONE_DETECTED from mhdp.tone_analysis i \n where i.device_id in (SELECT x.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))\n and i.data->>'$.tone_name' = 'NO_TONE_DETECTED'\ngroup by i.data->>'$.tone_name';"
    }
   ]
  },
  {
   "title": "Alarm Map",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as \"time\", sum(data->>'$.no_of_visits') as \"No. of BAR Visits\" , data->>'$.type_of_place' as \"Type of Place\"\nFROM mhdp.plugin_alarm_map x\nwhere x.device_id in (SELECT i.device_id FROM mhdp.device_id i where i.name in ($Patient_Name))\nand data->>'$.type_of_place' = 'BAR'\ngroup by timestamp, data->>'$.type_of_place'\norder by timestamp, data->>'$.type_of_place';\n"
    },
    {
     "rawSql": "SELECT timestamp as \"time\", sum(data->>'$.no_of_visits') as \"No. of LIQUOR STORE Visits\" , data->>'$.type_of_place' as \"Type of Place\"\nFROM mhdp.plugin_alarm_map x\nwhere x.device_id in (SELECT i.device_id FROM mhdp.device_id i where i.name in ($Patient_Name))\nand data->>'$.type_of_place' = 'LIQUOR_STORE'\ngroup by timestamp, data->>'$.type_of_place'\norder by timestamp, data->>'$.type_of_place';\n"
    }
   ]
  },
  {
   "title": "Noise Analysis",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "select  i.data->>'$.low_noise_time' as Low_Noise from `mhdp`.`plugin_noise_analysis` i\nwhere i.data->>'$.low_noise_time' != 0 and\ni.device_id in (SELECT x.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))"
    },
    {
     "rawSql": "select  i.data->>'$.moderate_noise_time' as Moderate_Noise from `mhdp`.`plugin_noise_analysis` i\nwhere i.data->>'$.moderate_noise_time' != 0 and\ni.device_id in (SELECT x.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))"
    },
    {
     "rawSql": "select  i.data->>'$.high_noise_time' as High_Noise from `mhdp`.`plugin_noise_analysis` i\nwhere i.data->>'$.high_noise_time' != 0 and\ni.device_id in (SELECT x.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))"
    },
    {
     "rawSql": "select i.data->>'$.is_harmful_inday' as High_Noise from `mhdp`.`plugin_noise_analysis` i\nwhere i.data->>'$.is_harmful_inday' != 0 and\ni.device_id in (SELECT x.device_id FROM mhdp.device_id x where x.name in ($Patient_Name))"
    }
   ]
  }
 ]
}